### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ghost** [Warren1001/attributehider#1]
timings
https://timings.aikar.co/?id=9ba99cd72644475bac4699e7a1a3136c

logs
```
[14:30:17] [Server thread/ERROR]: Could not pass event InventoryOpenEvent to AttributeHider v5.0.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1247]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1247]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1247]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) ~[patched_1.12.2.jar:git-Paper-1247]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) ~[patched_1.12.2.jar:git-Paper-1247]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:777) ~[patched_1.12.2.jar:git-Paper-1247]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:763) ~[patched_1.12.2.jar:git-Paper-1247]
	at net.minecraft.server.v1_12_R1.EntityPlayer.openTrade(EntityPlayer.java:863) ~[patched_1.12.2.jar:git-Paper-1247]
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftHumanEntity.openMerchant(CraftHumanEntity.java:395) ~[patched_1.12.2.jar:git-Paper-1247]
	at com.nisovin.shopkeepers.compat.v1_12_R1.NMSHandler.openTradeWindow(NMSHandler.java:61) ~[?:?]
	at com.nisovin.shopkeepers.ui.defaults.TradingHandler.openWindow(TradingHandler.java:62) ~[?:?]
	at com.nisovin.shopkeepers.ui.UIManager.requestUI(UIManager.java:77) ~[?:?]
	at com.nisovin.shopkeepers.Shopkeeper.openWindow(Shopkeeper.java:422) ~[?:?]
	at com.nisovin.shopkeepers.Shopkeeper.openTradingWindow(Shopkeeper.java:446) ~[?:?]
	at com.nisovin.shopkeepers.Shopkeeper.onPlayerInteraction(Shopkeeper.java:543) ~[?:?]
	at com.nisovin.shopkeepers.LivingEntityShopListener.onEntityInteract(LivingEntityShopListener.java:59) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:35) ~[patched_1.12.2.jar:git-Paper-1247]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1247]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1247]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) ~[patched_1.12.2.jar:git-Paper-1247]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) ~[patched_1.12.2.jar:git-Paper-1247]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1656) ~[patched_1.12.2.jar:git-Paper-1247]
	at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:49) ~[patched_1.12.2.jar:git-Paper-1247]
	at net.minecraft.server.v1_12_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.12.2.jar:git-Paper-1247]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1247]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.2.jar:git-Paper-1247]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [patched_1.12.2.jar:git-Paper-1247]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1247]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1247]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1247]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
	at com.kabryxis.attributehider.version.wrapper.entityvillager.impl.WrappedEntityVillagerv1_12_R1.setVillager(WrappedEntityVillagerv1_12_R1.java:18) ~[?:?]
	at com.kabryxis.attributehider.Remover.modify(Remover.java:99) ~[?:?]
	at com.kabryxis.attributehider.Remover.onInventoryOpen(Remover.java:147) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor663.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1247]
	... 32 more
```

**Comment by Warren1001** [comment]
I see now why Shopkeepers has a problem. A temporary solution (provided because this problem has been known) is to simply disable the villager interaction of my plugin. I will see if I can up with a solution but it's a difficult problem.

/e Check the latest version on the Spigot page, turned out to be a much easier fix than thought.
